<?= Load::lib("html"); ?>
<?= Load::lib("formulario"); ?>
<?php View::partial("ajax"); ?>
<style type="text/css"">
	
</style>
<div id="notificacion"></div>
<div id="formatable">á
	<?= Formulario::inicioAjax(isset($menu) ? "menu/modificar" : "menu/registrar", "contenido") ?>
		<table class="grayform" width="100%" height="135" border="0" align="center">
			<tbody>
				<tr style="background-color: #EEE">
					<td colspan="4" align="center">
					<label>
						<?= isset($menu) ? "Información del Menu" : "Nuevo Menu" ?> (Grupo de Ventanas)
						<hr />
					</label>
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td colspan="2">
						<?= Formulario::texto("titulo","","validate: required:true","class: text-input text-input-medium") ?>
						<span class="subtitulo">Nombre del Menu</span> 
					</td>
					<td>
						<?= Formulario::select("abierto",array("SI","NO"),"SI","validate: required:true","class: text-input select-small") ?>
						<span class="subtitulo">Abierto</span> 
					</td>
					<td>
						<?= Formulario::select("activo",array("SI","NO"),"SI","validate: required:true","class: text-input select-small") ?>
						<span class="subtitulo">Activo</span> 
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td colspan="4" align="right">
						<div class="buttons" style="float: right">
							<?= Formulario::submitBoton("Registrar Menu","positivo","miniconos/application_side_boxes.png") ?>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	<?= Formulario::fin(); ?>
	<br />
	<?= Formulario::inicioAjax(isset($menu) ? "menu/modificar" : "menu/registrar", "contenido") ?>
		<table class="grayform" width="100%" height="135" border="0" align="center">
			<tbody>
				<tr style="background-color: #EEE">
					<td colspan="4" align="center">
					<label>
						<?= isset($menu) ? "Información del Menu" : "Nuevo Menu" ?> (Grupo de Ventanas)
						<hr />
					</label>
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td colspan="2">
						<?= Formulario::select("titulo",array("Opcion 1","Opcion 2"),"","validate: required:true","class: text-input select-medium") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td>
						<?= Formulario::texto("titulo3","","validate: required:true","class: text-input text-input-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td>
						<?= Formulario::texto("titulo4","","validate: required:true","class: text-input text-input-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td>
						<?= Formulario::select("titulo",array("Opcion 1","Opcion 2"),"","validate: required:true","class: text-input select-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td>
						<?= Formulario::select("titulo",array("Opcion 1","Opcion 2"),"","validate: required:true","class: text-input select-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td>
						<?= Formulario::select("titulo",array("Opcion 1","Opcion 2"),"","validate: required:true","class: text-input select-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td>
						<?= Formulario::select("titulo",array("Opcion 1","Opcion 2"),"","validate: required:true","class: text-input select-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td>
						<?= Formulario::texto("titulo","","validate: required:true","class: text-input text-input-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td>
						<?= Formulario::texto("titulo2","","validate: required:true","class: text-input text-input-small") ?>
						<span class="subtitulo">Hola</span> 
					</td>
					<td colspan="2">
						<?= Formulario::texto("titulo6","","validate: required:true","class: text-input text-input-medium") ?>
						<span class="subtitulo">Hola</span>
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td colspan="2">
						<?= Formulario::texto("titulo5","","validate: required:true","class: text-input text-input-medium") ?>
						<span class="subtitulo">Hola</span>
					</td>
					<td colspan="2">
						<?= Formulario::texto("titulo6","","validate: required:true","class: text-input text-input-medium") ?>
						<span class="subtitulo">Hola</span>
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td colspan="4" align="right">
						<div class="buttons" style="float: right">
							<?= Formulario::submitBoton("Registrar Menu","positivo","miniconos/application_side_boxes.png") ?>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	<?= Formulario::fin(); ?>
</div>