<?= Load::lib("html"); ?>
<?= Load::lib("formulario"); ?>
<?php View::partial("ajax"); ?>
<div id="notificacion"></div>
<div id="formatable">
	<?= Formulario::inicioAjax("menu/registrar", "contenido") ?>
		<table width="100%" height="135" border="0" align="center">
			<tbody>
				<tr style="background-color: #EEE">
					<td colspan="2" align="center">
					<label>
						Nuevo Menu (Grupo de Ventanas)
						<hr />
					</label>
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td width="20%">Titulo: </td>
					<td  width="30%">
						<?= Formulario::texto("titulo","","validate: required:true","class: text-input large-input") ?>
					</td>
					<td width="20%">Titulo: </td>
					<td  width="30%">
						<?= Formulario::texto("titulo","","validate: required:true","class: text-input large-input") ?>
					</td>
				</tr>
				<tr style="background-color: #EEE">
					<td width="30%"></td>
					<td width="70%" align="right">
						<div class="buttons" style="float: right">
							<?= Formulario::submitBoton("Registrar Menu","positivo","miniconos/application_side_boxes.png") ?>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	<?= Formulario::fin(); ?>
</div>