Santiago, Chile a 11 de Junio de 2012
<br />CARTA PODER
<br />
<br />A quien corresponda:
<br /><br />Por medio de la presente YO el Sr. Ramiro Alonso Vera Contreras con RUT: 22.966.533-2 otorgo a la Srta. Miriam Margarita Ortega Torres y con RUT: 23.581.105-7 poder amplio, cumplido y bastante para que a mi nombre y representación pueda realizar los trámites correspondientes para la recepción y legalización de mi titulo de Magister en Tecnologías de la Información emitido por la Universidad de Chile.
<br /><br />Estos trámites serán realizados ante las siguientes entidades:
<br /><br />Universidad de Chile
<br />Ministerio de Educación
<br />Ministerio de Relaciones Exteriores
<br />Sección Consular de la Embajada de México en Chile
<br /><br />Una vez mencionado esto, agradezco a usted por su atención y el apoyo en la correcta realización de estos trámites.
<br />
<br />ATENTAMENTE
<br />
<br />
<br />Ing. Ramiro Alonso Vera Contreras